[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npx --yes serve -s dist -l tcp://0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
